staging:
  database: tripart-stagingDB
  username: tripartDEVdbuser
  password: kupUbreCRaCe2ra
  host: aba1753a40cd6ed8fd855f844ee36ddd04fdb2aa.rackspaceclouddb.com
production:
  database: tripart-productionDB
  username: tripartdbuser
  password: 'hak!rut8ab3ecespemeDr2hu@'
  host: aba1753a40cd6ed8fd855f844ee36ddd04fdb2aa.rackspaceclouddb.com
local:
  database: tripartiteDB
  username: root
  password: root
  host: localhost